name: flutter_demo2
description: flutter demo2 base on getx

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  date_format: ^2.0.7  
  easy_refresh: ^3.0.4+2 # 下拉刷新1    
  flutter_screenutil: ^5.3.1
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/
